MoviesManag/force-app/main/default/objects/Movie__c/Movie__c.object-meta.xml
<CustomObject>
    <label>Movie</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Movies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MoviesManag/force-app/main/default/objects/Movie__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Horror</fullName>
            </value>
            <value>
                <fullName>Adventure</fullName>
            </value>
            <value>
                <fullName>Action</fullName>
            </value>
            <value>
                <fullName>Drama</fullName>
            </value>
            <value>
                <fullName>Comedy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MoviesManag/force-app/main/default/classes/DM001_MoviesActors.cls
public with sharing class DM001_MoviesActors {

    public DM001_MoviesActors() {

    }

    /**
     * Get Movies by search key
     */
    //method imperatif  ====> Cacheable=false
    @AuraEnabled(Cacheable=false)
    public static List<Movie__c> getMoviesByKey(String searchKey){

        List<Movie__c> moviesResult = [Select Name,category__c from Movie__c where Name like :searchKey ];
        return moviesResult;

    }



}