MoviesManag/force-app/main/default/objects/Actor__c/Actor__c.object-meta.xml
<CustomObject>
    <label>Actor</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Actors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MoviesManag/force-app/main/default/objects/Actor__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MoviesManag/force-app/main/default/objects/Movie__c/Movie__c.object-meta.xml
<CustomObject>
    <label>Movie</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Movies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MoviesManag/force-app/main/default/objects/Movie__c/fields/Female_Actors_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Female_Actors_Percentage__c</fullName>
    <label>Female Actors Percentage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

MoviesManag/force-app/main/default/objects/Movie__c/fields/Male_Actors_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Male_Actors_Percentage__c</fullName>
    <label>Male Actors Percentage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

MoviesManag/force-app/main/default/classes/MovieActorTriggerHandler.cls
public with sharing class MovieActorTriggerHandler {

    public MovieActorTriggerHandler() {}

    public static void calculateGenderPercentage(List<Actor__c> movieActors,Id currentMovieId){


        Integer actorsNumber = movieActors.size();
        Integer femaleActorsNumber=0;
        Integer maleActorsNumber=0;

  
        
        for(Actor__c actor:movieActors){

            if(actor.Gender__c == System.Label.Gender_Female){
                femaleActorsNumber++;
                system.debug(femaleActorsNumber);
            }else {
                maleActorsNumber++;
                system.debug(maleActorsNumber);
            }
        }

        Movie__c currentMovie = new Movie__c(Id=currentMovieId);
        
        currentMovie.Female_Actors_Percentage__c = (femaleActorsNumber*100)/actorsNumber;
        currentMovie.Male_Actors_Percentage__c = (maleActorsNumber*100)/actorsNumber;
        update currentMovie;
        
    }

}