MoviesManag/force-app/main/default/objects/Actor__c/Actor__c.object-meta.xml
<CustomObject>
    <label>Actor</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Actors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MoviesManag/force-app/main/default/objects/Movie__c/Movie__c.object-meta.xml
<CustomObject>
    <label>Movie</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Movies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MoviesManag/force-app/main/default/objects/Movie__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Horror</fullName>
            </value>
            <value>
                <fullName>Adventure</fullName>
            </value>
            <value>
                <fullName>Action</fullName>
            </value>
            <value>
                <fullName>Drama</fullName>
            </value>
            <value>
                <fullName>Comedy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MoviesManag/force-app/main/default/objects/Movie__c/fields/Release_date__c.field-meta.xml
<CustomField>
    <fullName>Release_date__c</fullName>
    <label>Release date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

MoviesManag/force-app/main/default/objects/MovieActor__c/MovieActor__c.object-meta.xml
<CustomObject>
    <label>MovieActor</label>
    <nameField>
        <label>MovieActor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MoviesActors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

MoviesManag/force-app/main/default/objects/MovieActor__c/fields/Movies__c.field-meta.xml
<CustomField>
    <fullName>Movies__c</fullName>
    <label>Movie</label>
    <referenceTo>Movie__c</referenceTo>
    <relationshipLabel>MoviesActors</relationshipLabel>
    <relationshipName>MoviesActors</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

MoviesManag/force-app/main/default/classes/SM001_MoviesActors.cls
public with sharing class SM001_MoviesActors {

    public SM001_MoviesActors() {

    }

    @AuraEnabled
    public static void createMovie(NewMovie newMovie,List<String> movieActorsIds) {

         Movie__c newMovieToinsert = new Movie__c();

         newMovieToinsert.Name = newMovie.name;
         newMovieToinsert.category__c = newMovie.category;
         newMovieToinsert.Description__c = newMovie.description;
         newMovieToinsert.Rating__c = newMovie.rating;
         newMovieToinsert.Release_date__c = newMovie.releaseDate;
        

         insert newMovieToinsert;
       

         List<MovieActor__c> movieActorsToinsert  =new List<MovieActor__c>();

         for(String idActor : movieActorsIds){
            MovieActor__c movieActor =new MovieActor__c();
            movieActor.Actor__c=idActor;
            movieActor.Movies__c=newMovieToinsert.Id;
            movieActorsToinsert.add(movieActor);

         }
        insert movieActorsToinsert;

    
    }

    @AuraEnabled
    public static List<Movie__c> getMoviesByKey(String movieName){
            System.debug('movieName'+movieName);
            return DM001_MoviesActors.getMoviesByKey(movieName); 
    }

    @AuraEnabled(Cacheable=true)
    public static List<Movie__c> getAllMovies(){      
            return DM001_MoviesActors.getAllMovies();   
    }


    //wrapper class Entity 
    public class NewMovie{

        public newMovie(){
    
        }

        @auraEnabled
        public String name {get;set;}
        @auraEnabled
        public String category {get;set;}
        @auraEnabled
        public String  description{get;set;}
        @auraEnabled
        public Integer  rating {get;set;}
        @AuraEnabled
        public Date releaseDate {get;set;}

      
    }
}